# This is an example Pod definition to demonstrates
# how to use inline PMEM csi volumes.
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app-inline-volume
spec:
  # The 'pmem-csi-driver-test' container runs apps as user/group 1000/1000.
  # This security context causes permissions of volume mounts
  # to be adapted accordingly, see
  # https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  securityContext:
    fsGroup: 1000
  containers:
    - name: my-frontend
      image: intel/pmem-csi-driver-test:v0.9.1
      command: [ "sleep", "100000" ]
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume
  volumes:
  - name: my-csi-volume
    csi:
      driver: pmem-csi.intel.com
      fsType: "xfs"
      volumeAttributes:
        size: "2Gi"

